services:
  - type: web
    name: garage-app
    runtime: php
    buildCommand: |
      php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      php composer-setup.php
      php composer.phar install --no-dev
      php artisan key:generate --force
      php artisan storage:link
      php artisan migrate --force
    startCommand: "php artisan serve --host=0.0.0.0 --port=8080"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
